### ISSUE TITLE
svg大小匹配存在bug

### ISSUE THREAD

**Issue by WalleV** [weixin/gulp-lazyimagecss#2]
你好，我在使用过程中发现了一个问题， 从PS导出的svg属性并不带px单位， 类似于下面的示例。

``` svg
<svg width="200" height="200" viewBox="0 0 200 200"> ...
```

看了下源码， 在getSVGImageSize方法里面， 是直接以px作为结束的，所以在匹配的时候会返回为**null**导致工作流停止。

希望能尽快修复这个bug，感谢！

**Comment by littledu** [comment]
谢谢 @EveCoffee  新版本已修复
